import 'dart:convert';
import 'dart:io';

typedef JsonMap = Map<String, dynamic>;

const _manifestPath = 'tool/visibility/visibility_manifest.json';
const _generatedNotice =
    'Generated by dart run tool/visibility/generate_visibility.dart. '
    'Edit tool/visibility/visibility_manifest.json instead.';

void main(List<String> args) {
  final check = args.contains('--check');
  final manifest = _readManifest();
  final outputs = _generateOutputs(manifest);

  var failed = false;
  for (final entry in outputs.entries) {
    final file = File(entry.key);
    if (check) {
      if (!file.existsSync()) {
        stderr.writeln('Missing generated file: ${entry.key}');
        failed = true;
        continue;
      }
      final current = file.readAsStringSync();
      if (current != entry.value) {
        stderr.writeln('Generated file is stale: ${entry.key}');
        failed = true;
      }
    } else {
      file.parent.createSync(recursive: true);
      file.writeAsStringSync(entry.value);
      stdout.writeln('wrote ${entry.key}');
    }
  }

  if (check && failed) {
    stderr.writeln(
      'Run `dart run tool/visibility/generate_visibility.dart` '
      'and commit the generated files.',
    );
    exitCode = 1;
  } else if (check) {
    stdout.writeln('Visibility files are in sync.');
  }
}

JsonMap _readManifest() {
  final file = File(_manifestPath);
  if (!file.existsSync()) {
    throw StateError('Missing $_manifestPath');
  }
  return jsonDecode(file.readAsStringSync()) as JsonMap;
}

Map<String, String> _generateOutputs(JsonMap manifest) {
  final outputs = <String, String>{
    'llms.txt': _llms(manifest),
    'llms-full.txt': _llmsFull(manifest),
    'identity.json': _identityJson(manifest),
    'developer-ai.txt': _developerAi(manifest),
    'faq-ai.txt': _faqAi(manifest),
    'ai.txt': _aiGuidance(manifest),
    'robots-ai.txt': _robotsAi(manifest),
    'robots.txt': _robots(manifest),
    '.github/copilot-instructions.md': _copilotInstructions(manifest),
    '.github/instructions/pqforge-crypto.instructions.md':
        _copilotCryptoInstructions(manifest),
    '.cursor/rules/pqforge.mdc': _cursorRule(manifest),
    '.windsurfrules': _windsurfRules(manifest),
    'site/index.html': _siteIndex(manifest),
    'site/404.html': _siteNotFound(manifest),
    'site/styles.css': _siteCss(),
    'site/assets/pqforge-protocol.svg': _protocolSvg(),
    'site/favicon.svg': _faviconSvg(),
    'site/sitemap.xml': _sitemap(manifest),
  };

  for (final path in [
    'llms.txt',
    'llms-full.txt',
    'identity.json',
    'developer-ai.txt',
    'faq-ai.txt',
    'ai.txt',
    'robots-ai.txt',
    'robots.txt',
  ]) {
    outputs['site/$path'] = outputs[path]!;
  }

  return outputs;
}

String _llms(JsonMap manifest) {
  final project = _map(manifest['project']);
  final docs = _maps(manifest['docs']);
  final recipes = _maps(manifest['recipes']);
  final doesNotProvide = _strings(manifest['does_not_provide']);
  final forbidden = _strings(
    _map(manifest['evidence_boundary'])['forbidden_claims'],
  );

  final buffer = StringBuffer()
    ..writeln(_mdComment())
    ..writeln('# ${project['short_title']}')
    ..writeln()
    ..writeln('> ${project['tagline']}')
    ..writeln(
      '> Version ${project['version']}; ${project['license']} licensed.',
    )
    ..writeln()
    ..writeln(project['summary'])
    ..writeln()
    ..writeln('## Start Here')
    ..writeln()
    ..writeln('- Website: ${project['canonical_url']}')
    ..writeln('- Repository: ${project['repository']}')
    ..writeln('- Package: ${project['pub_dev']}')
    ..writeln('- API docs: ${project['api_docs']}')
    ..writeln('- Wiki: ${project['wiki']}')
    ..writeln()
    ..writeln('## Key Boundary')
    ..writeln()
    ..writeln(
      '- pqforge composes pqcrypto ML-KEM/ML-DSA with AEAD, KDF, custody, recipes, and CLI workflows.',
    )
    ..writeln('- It is not a validated cryptographic module.')
    ..writeln('- It does not provide:');

  for (final item in doesNotProvide) {
    buffer.writeln('  - $item');
  }

  buffer
    ..writeln()
    ..writeln('## Never Say')
    ..writeln();

  for (final claim in forbidden) {
    buffer.writeln('- $claim');
  }

  buffer
    ..writeln()
    ..writeln('## Recipes')
    ..writeln();

  for (final recipe in recipes) {
    buffer.writeln(
      '- ${recipe['name']}: ${recipe['apis']} (${recipe['apps']}).',
    );
  }

  buffer
    ..writeln()
    ..writeln('## Docs')
    ..writeln();

  for (final doc in docs) {
    buffer.writeln(
      '- [${doc['title']}](${_repoBlob(project, doc['url'] as String)}): '
      '${doc['description']}',
    );
  }

  return buffer.toString();
}

String _llmsFull(JsonMap manifest) {
  final project = _map(manifest['project']);
  final capabilities = _strings(manifest['capabilities']);
  final doesNotProvide = _strings(manifest['does_not_provide']);
  final evidence = _map(manifest['evidence_boundary']);
  final profiles = _maps(manifest['profiles']);
  final recipes = _maps(manifest['recipes']);
  final docs = _maps(manifest['docs']);
  final commands = _strings(manifest['validation_commands']);

  final buffer = StringBuffer()
    ..writeln(_mdComment())
    ..writeln('# ${project['title']}')
    ..writeln()
    ..writeln('Canonical URL: ${project['canonical_url']}')
    ..writeln('Repository: ${project['repository']}')
    ..writeln('Package: ${project['pub_dev']}')
    ..writeln('API docs: ${project['api_docs']}')
    ..writeln('Version: ${project['version']}')
    ..writeln()
    ..writeln('## Identity')
    ..writeln()
    ..writeln(project['summary'])
    ..writeln()
    ..writeln('## Capabilities')
    ..writeln();

  for (final item in capabilities) {
    buffer.writeln('- $item');
  }

  buffer
    ..writeln()
    ..writeln('## Does Not Provide')
    ..writeln();

  for (final item in doesNotProvide) {
    buffer.writeln('- $item');
  }

  buffer
    ..writeln()
    ..writeln('## Evidence Boundary')
    ..writeln()
    ..writeln(evidence['summary'])
    ..writeln()
    ..writeln('Allowed claims:');
  for (final claim in _strings(evidence['allowed_claims'])) {
    buffer.writeln('- $claim');
  }
  buffer.writeln();
  buffer.writeln('Forbidden claims:');
  for (final claim in _strings(evidence['forbidden_claims'])) {
    buffer.writeln('- $claim');
  }

  buffer
    ..writeln()
    ..writeln('## Profiles')
    ..writeln();
  for (final profile in profiles) {
    buffer.writeln(
      '- ${profile['name']}: ${profile['kem']} + ${profile['signature']} for ${profile['use']}.',
    );
  }

  buffer
    ..writeln()
    ..writeln('## Recipe Catalog')
    ..writeln();
  for (final recipe in recipes) {
    buffer
      ..writeln('### ${recipe['name']}')
      ..writeln()
      ..writeln('- Surface: ${recipe['surface']}')
      ..writeln('- Apps: ${recipe['apps']}')
      ..writeln('- APIs: ${recipe['apis']}')
      ..writeln('- Caveat: ${recipe['caveat']}')
      ..writeln();
  }

  buffer
    ..writeln('## Docs')
    ..writeln();
  for (final doc in docs) {
    buffer.writeln(
      '- [${doc['title']}](${_repoBlob(project, doc['url'] as String)}): '
      '${doc['description']}',
    );
  }

  buffer
    ..writeln()
    ..writeln('## Validation')
    ..writeln();
  for (final command in commands) {
    buffer.writeln('- `$command`');
  }

  return buffer.toString();
}

String _identityJson(JsonMap manifest) {
  final project = _map(manifest['project']);
  final identity = <String, Object?>{
    '@context': 'https://schema.org',
    '@type': 'SoftwareSourceCode',
    'name': project['short_title'],
    'alternateName': project['title'],
    'description': project['summary'],
    'url': project['canonical_url'],
    'codeRepository': project['repository'],
    'programmingLanguage': 'Dart',
    'runtimePlatform': ['Dart VM', 'Flutter', 'Serverpod', 'CLI'],
    'license': project['license'],
    'softwareVersion': project['version'],
    'applicationCategory': 'Cryptography composition library',
    'keywords': _strings(manifest['keywords']),
    'maintainer': {'@type': 'Organization', 'name': project['maintainer']},
    'sameAs': [
      project['repository'],
      project['pub_dev'],
      project['api_docs'],
      project['wiki'],
    ],
    'capabilities': _strings(manifest['capabilities']),
    'doesNotProvide': _strings(manifest['does_not_provide']),
    'evidenceBoundary': manifest['evidence_boundary'],
    'recipes': manifest['recipes'],
    'generatedBy': _generatedNotice,
    'dateModified': manifest['last_updated'],
  };
  return '${const JsonEncoder.withIndent('  ').convert(identity)}\n';
}

String _developerAi(JsonMap manifest) {
  final project = _map(manifest['project']);
  final commands = _strings(manifest['validation_commands']);
  final recipes = _maps(manifest['recipes']);

  final buffer = StringBuffer()
    ..writeln(_mdComment())
    ..writeln('# Developer AI Guidance For ${project['short_title']}')
    ..writeln()
    ..writeln(
      'Use this file when an AI coding agent needs scoped pqforge context.',
    )
    ..writeln()
    ..writeln('## Core Rule')
    ..writeln()
    ..writeln(
      'pqforge is an application composition package. Keep claims scoped to composition around pqcrypto; do not claim validation or certification.',
    )
    ..writeln()
    ..writeln('## Recipe Surfaces')
    ..writeln();
  for (final recipe in recipes) {
    buffer.writeln('- ${recipe['name']}: ${recipe['apis']}');
  }
  buffer
    ..writeln()
    ..writeln('## Required Verification')
    ..writeln();
  for (final command in commands) {
    buffer.writeln('- `$command`');
  }
  return buffer.toString();
}

String _faqAi(JsonMap manifest) {
  final faq = _maps(manifest['faq']);
  final buffer = StringBuffer()..writeln(_mdComment());
  for (final item in faq) {
    buffer
      ..writeln('## ${item['question']}')
      ..writeln()
      ..writeln(item['answer'])
      ..writeln();
  }
  return buffer.toString();
}

String _aiGuidance(JsonMap manifest) {
  final evidence = _map(manifest['evidence_boundary']);
  final buffer = StringBuffer()
    ..writeln(_mdComment())
    ..writeln('# AI Usage Policy For pqforge')
    ..writeln()
    ..writeln('Allowed summaries:')
    ..writeln(
      '- pqforge composes pqcrypto ML-KEM and ML-DSA for app workflows.',
    )
    ..writeln(
      '- pqforge includes AEAD, KDF, key wrapping, recipes, CLI, and hybrid helpers.',
    )
    ..writeln('- pqforge is not a validated cryptographic module.')
    ..writeln()
    ..writeln('Forbidden claims:');
  for (final claim in _strings(evidence['forbidden_claims'])) {
    buffer.writeln('- $claim');
  }
  return buffer.toString();
}

String _robotsAi(JsonMap manifest) {
  final project = _map(manifest['project']);
  return '''
User-agent: *
Allow: /

# Preferred AI entrypoints
Sitemap: ${project['canonical_url']}sitemap.xml
LLMS: ${project['canonical_url']}llms.txt
LLMS-Full: ${project['canonical_url']}llms-full.txt
''';
}

String _robots(JsonMap manifest) {
  final project = _map(manifest['project']);
  return '''
User-agent: *
Allow: /

Sitemap: ${project['canonical_url']}sitemap.xml
''';
}

String _copilotInstructions(JsonMap manifest) {
  final project = _map(manifest['project']);
  return '''
${_mdComment()}
# Copilot Instructions For ${project['short_title']}

- Treat `doc/` as the canonical documentation root.
- Keep generated visibility files in sync with `dart run tool/visibility/generate_visibility.dart`.
- Prefer named recipe helpers over hand-rolled message framing.
- Use wrapped secret keys for CLI examples.
- Do not claim FIPS validation, CMVP validation, certification, hard constant-time behavior, or hard memory erasure.
- Do not add RC4 or unauthenticated encryption.
''';
}

String _copilotCryptoInstructions(JsonMap manifest) {
  final recipes = _maps(manifest['recipes']);
  final buffer = StringBuffer()
    ..writeln(_mdComment())
    ..writeln('# pqforge Crypto Composition Rules')
    ..writeln()
    ..writeln('- ML-KEM establishes a shared secret; KEM-DEM uses HKDF + AEAD.')
    ..writeln('- ML-DSA signs; AES encrypts and never signs.')
    ..writeln(
      '- Public-key trust, identity vetting, and replay stores belong to the application.',
    )
    ..writeln('- Use these recipe surfaces:');
  for (final recipe in recipes) {
    buffer.writeln('  - ${recipe['name']}: ${recipe['apis']}');
  }
  return buffer.toString();
}

String _cursorRule(JsonMap manifest) {
  final project = _map(manifest['project']);
  return '''
---
description: pqforge repository guidance
alwaysApply: true
---

$_generatedNotice

Use `${project['short_title']}` as a composition package, not a primitive package.
Keep docs, README, wiki, and site claim boundaries synchronized.
Run `dart run tool/visibility/generate_visibility.dart --check` after visibility edits.
''';
}

String _windsurfRules(JsonMap manifest) {
  final project = _map(manifest['project']);
  return '''
$_generatedNotice

Repository: ${project['repository']}

Rules:
- Use named pqforge recipe helpers for app workflows.
- Keep CLI secret keys wrapped in examples.
- Keep generated visibility files current.
- Avoid validation/certification overclaims.
''';
}

String _siteIndex(JsonMap manifest) {
  final project = _map(manifest['project']);
  final capabilities = _strings(manifest['capabilities']);
  final recipes = _maps(manifest['recipes']);
  final docs = _maps(manifest['docs']);
  final profiles = _maps(manifest['profiles']);
  final faq = _maps(manifest['faq']);

  return '''
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${_html(project['title'] as String)}</title>
  <meta name="description" content="${_html(project['summary'] as String)}">
  <link rel="icon" href="favicon.svg" type="image/svg+xml">
  <link rel="stylesheet" href="styles.css">
  <script type="application/ld+json">${jsonEncode(jsonDecode(_identityJson(manifest)))}</script>
</head>
<body>
  <header class="topbar">
    <a class="brand" href="#top" aria-label="pqforge home">
      <span class="brand-mark">PQ</span>
      <span>pqforge</span>
    </a>
    <nav aria-label="Primary">
      <a href="#recipes">Recipes</a>
      <a href="#cli">CLI</a>
      <a href="#use-cases">Use cases</a>
      <a href="#docs">Docs</a>
    </nav>
  </header>

  <main id="top">
    <section class="hero">
      <div class="hero-copy">
        <p class="eyebrow">Post-quantum application recipes for Dart</p>
        <h1>Encrypt files, folders, text, media, webhooks, tokens, and server sessions.</h1>
        <p class="lede">${_html(project['summary'] as String)}</p>
        <div class="hero-actions">
          <a class="button primary" href="#cli">Use the CLI</a>
          <a class="button secondary" href="#recipes">Explore recipes</a>
        </div>
      </div>
      <figure class="hero-visual">
        <img src="assets/pqforge-protocol.svg" alt="pqforge recipe pipeline from payloads to post-quantum envelopes">
      </figure>
    </section>

    <section class="signal-grid" aria-label="Package signals">
      <div><strong>3</strong><span>ML-KEM profiles</span></div>
      <div><strong>3</strong><span>ML-DSA profiles</span></div>
      <div><strong>11</strong><span>named recipes</span></div>
      <div><strong>1</strong><span>universal CLI</span></div>
    </section>

    <section id="recipes" class="section">
      <div class="section-heading">
        <p class="eyebrow">Recipe catalog</p>
        <h2>Build with named operations, not ad hoc crypto glue.</h2>
      </div>
      <div class="recipes">
        ${recipes.map(_recipeCard).join('\n')}
      </div>
    </section>

    <section id="cli" class="section split">
      <div>
        <p class="eyebrow">Universal CLI</p>
        <h2>Local files and server jobs get the same envelope model.</h2>
        <p>Generate reusable public keys and wrapped secret keys, then encrypt or sign files, folders, text, and media without writing application code.</p>
      </div>
      <pre class="terminal"><code>export PQFORGE_PASSPHRASE='from-your-secret-manager'
dart run pqforge keygen --profile maximum --key-id vault --out-dir keys --passphrase-env PQFORGE_PASSPHRASE
dart run pqforge encrypt-folder --recipient-public keys/vault.kem.public.json --in-dir ./records --out-dir ./records.pqf
dart run pqforge decrypt-folder --recipient-secret keys/vault.kem.secret.wrapped.json --passphrase-env PQFORGE_PASSPHRASE --in-dir ./records.pqf --out-dir ./records.open
dart run pqforge sign --kind media --signer-secret keys/vault.sign.secret.wrapped.json --passphrase-env PQFORGE_PASSPHRASE --in cover.png --mime-type image/png --out cover.sig.json</code></pre>
    </section>

    <section id="use-cases" class="section">
      <div class="section-heading">
        <p class="eyebrow">Use cases</p>
        <h2>From local vaults to server sessions.</h2>
      </div>
      <div class="use-cases">
        ${recipes.map((recipe) => '<div><h3>${_html(recipe['name'] as String)}</h3><p>${_html(recipe['apps'] as String)}</p></div>').join('\n')}
      </div>
    </section>

    <section class="section profiles">
      <div class="section-heading">
        <p class="eyebrow">Profiles</p>
        <h2>Pick a security margin that matches the lifetime.</h2>
      </div>
      <div class="profile-grid">
        ${profiles.map((profile) => '<div><h3>${_html(profile['name'] as String)}</h3><p>${_html(profile['kem'] as String)} + ${_html(profile['signature'] as String)}</p><span>${_html(profile['use'] as String)}</span></div>').join('\n')}
      </div>
    </section>

    <section id="docs" class="section docs">
      <div class="section-heading">
        <p class="eyebrow">Documentation</p>
        <h2>Everything users and agents need to stay inside the boundary.</h2>
      </div>
      <div class="doc-grid">
        ${docs.map((doc) => _docCard(project, doc)).join('\n')}
      </div>
    </section>

    <section class="section boundary">
      <div>
        <p class="eyebrow">Claim boundary</p>
        <h2>Composition, not certification.</h2>
        <p>pqforge provides application composition around pqcrypto evidence. It does not claim CMVP/FIPS 140 validation, hard constant-time Dart behavior, or hard memory erasure. RC4 is rejected.</p>
      </div>
      <ul>
        ${capabilities.take(6).map((item) => '<li>${_html(item)}</li>').join('\n')}
      </ul>
    </section>

    <section class="section faq">
      <div class="section-heading">
        <p class="eyebrow">FAQ</p>
        <h2>Answers before integration.</h2>
      </div>
      ${faq.map((item) => '<details><summary>${_html(item['question'] as String)}</summary><p>${_html(item['answer'] as String)}</p></details>').join('\n')}
    </section>
  </main>

  <footer>
    <span>Generated from tool/visibility/visibility_manifest.json</span>
    <a href="${_html(project['repository'] as String)}">GitHub</a>
    <a href="${_html(project['pub_dev'] as String)}">pub.dev</a>
    <a href="${_html(project['wiki'] as String)}">Wiki</a>
  </footer>
</body>
</html>
''';
}

String _docCard(JsonMap project, JsonMap doc) {
  final href = _repoBlob(project, doc['url'] as String);
  return '<a href="${_html(href)}"><strong>${_html(doc['title'] as String)}</strong><span>${_html(doc['description'] as String)}</span></a>';
}

String _recipeCard(JsonMap recipe) {
  return '''
<article>
  <span>${_html(recipe['surface'] as String)}</span>
  <h3>${_html(recipe['name'] as String)}</h3>
  <p>${_html(recipe['apps'] as String)}</p>
  <code>${_html(recipe['apis'] as String)}</code>
</article>
''';
}

String _siteNotFound(JsonMap manifest) {
  final project = _map(manifest['project']);
  return '''
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Not found - ${_html(project['short_title'] as String)}</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body class="not-found">
  <main>
    <p class="eyebrow">404</p>
    <h1>This pqforge page is not here.</h1>
    <p>Start from the generated visibility homepage.</p>
    <a class="button primary" href="index.html">Open pqforge</a>
  </main>
</body>
</html>
''';
}

String _siteCss() {
  return r'''
:root {
  color-scheme: dark;
  --ink: #f7fbff;
  --muted: #9fb1c7;
  --panel: rgba(9, 17, 29, .78);
  --panel-strong: rgba(15, 29, 46, .94);
  --line: rgba(174, 209, 255, .18);
  --cyan: #52e0d5;
  --gold: #f5c35b;
  --rose: #ff6f91;
  --green: #84e68b;
  --bg: #07111d;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

* { box-sizing: border-box; }

html { scroll-behavior: smooth; }

body {
  margin: 0;
  background:
    linear-gradient(120deg, rgba(82, 224, 213, .16), transparent 30%),
    linear-gradient(200deg, rgba(245, 195, 91, .12), transparent 35%),
    var(--bg);
  color: var(--ink);
}

a { color: inherit; text-decoration: none; }

.topbar {
  position: sticky;
  top: 0;
  z-index: 10;
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 24px;
  padding: 14px clamp(20px, 4vw, 56px);
  background: rgba(7, 17, 29, .82);
  border-bottom: 1px solid var(--line);
  backdrop-filter: blur(18px);
}

.brand { display: inline-flex; align-items: center; gap: 10px; font-weight: 800; }
.brand-mark {
  display: grid;
  place-items: center;
  width: 36px;
  height: 36px;
  border-radius: 8px;
  background: linear-gradient(135deg, var(--cyan), var(--gold));
  color: #06111d;
  font-size: 13px;
}

nav { display: flex; flex-wrap: wrap; gap: 18px; color: var(--muted); font-size: 14px; }
nav a:hover { color: var(--ink); }

.hero {
  min-height: min(720px, 76vh);
  display: grid;
  grid-template-columns: minmax(0, .95fr) minmax(320px, 560px);
  gap: clamp(28px, 5vw, 72px);
  align-items: center;
  padding: clamp(36px, 5vw, 68px) clamp(20px, 5vw, 72px) 34px;
}

.hero-copy { max-width: 760px; }
.eyebrow {
  margin: 0 0 12px;
  color: var(--cyan);
  text-transform: uppercase;
  font-size: 12px;
  font-weight: 800;
  letter-spacing: .12em;
}

h1, h2, h3 { margin: 0; letter-spacing: 0; line-height: 1.04; }
h1 { font-size: clamp(42px, 4.2vw, 64px); max-width: 760px; }
h2 { font-size: clamp(30px, 4vw, 54px); }
h3 { font-size: 20px; }

.lede {
  max-width: 760px;
  margin: 18px 0 0;
  color: var(--muted);
  font-size: clamp(17px, 1.6vw, 19px);
  line-height: 1.65;
}

.hero-actions { display: flex; flex-wrap: wrap; gap: 12px; margin-top: 24px; }
.button {
  display: inline-flex;
  min-height: 44px;
  align-items: center;
  justify-content: center;
  padding: 0 18px;
  border-radius: 8px;
  font-weight: 800;
}
.primary { background: var(--cyan); color: #06111d; }
.secondary { border: 1px solid var(--line); color: var(--ink); background: rgba(255,255,255,.04); }

.hero-visual {
  margin: 0;
  min-height: 360px;
  border: 1px solid var(--line);
  border-radius: 8px;
  overflow: hidden;
  background: rgba(255,255,255,.04);
  box-shadow: 0 30px 90px rgba(0,0,0,.35);
}
.hero-visual img { width: 100%; height: 100%; display: block; object-fit: cover; }

.signal-grid {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 1px;
  margin: 0 clamp(20px, 5vw, 72px);
  border: 1px solid var(--line);
  background: var(--line);
}
.signal-grid div { padding: 24px; background: var(--panel); }
.signal-grid strong { display: block; font-size: 34px; color: var(--gold); }
.signal-grid span { color: var(--muted); }

.section { padding: clamp(58px, 8vw, 110px) clamp(20px, 5vw, 72px); }
.section-heading { max-width: 760px; margin-bottom: 28px; }
.section-heading h2 + p { color: var(--muted); }

.recipes, .use-cases, .doc-grid, .profile-grid {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 14px;
}

.recipes article, .use-cases div, .doc-grid a, .profile-grid div, details {
  min-height: 100%;
  padding: 22px;
  border: 1px solid var(--line);
  border-radius: 8px;
  background: var(--panel);
}
.recipes article span, .profile-grid span, .doc-grid span {
  display: block;
  color: var(--muted);
  margin-top: 10px;
  line-height: 1.55;
}
.recipes p, .use-cases p, .boundary p, details p { color: var(--muted); line-height: 1.6; }
code {
  display: block;
  margin-top: 14px;
  color: var(--green);
  white-space: normal;
  overflow-wrap: anywhere;
}

.split {
  display: grid;
  grid-template-columns: minmax(0, .75fr) minmax(320px, 1.25fr);
  gap: 30px;
  align-items: start;
  background: rgba(82, 224, 213, .06);
}
.terminal {
  margin: 0;
  padding: 22px;
  border-radius: 8px;
  border: 1px solid var(--line);
  background: #050b12;
  color: #d5f7ef;
  overflow-x: auto;
  line-height: 1.7;
}
.terminal code { margin: 0; white-space: pre; }

.boundary {
  display: grid;
  grid-template-columns: .8fr 1.2fr;
  gap: 24px;
  background: rgba(245, 195, 91, .06);
}
.boundary ul {
  margin: 0;
  padding: 0;
  display: grid;
  gap: 10px;
  list-style: none;
}
.boundary li {
  padding: 14px 16px;
  border: 1px solid var(--line);
  border-radius: 8px;
  background: var(--panel);
}

details { margin-bottom: 10px; }
summary { cursor: pointer; font-weight: 800; }

footer {
  display: flex;
  flex-wrap: wrap;
  gap: 18px;
  justify-content: space-between;
  padding: 28px clamp(20px, 5vw, 72px);
  color: var(--muted);
  border-top: 1px solid var(--line);
}

.not-found main { max-width: 720px; margin: 18vh auto; padding: 24px; }

@media (max-width: 900px) {
  .hero, .split, .boundary { grid-template-columns: 1fr; }
  .recipes, .use-cases, .doc-grid, .profile-grid, .signal-grid { grid-template-columns: 1fr; }
  .topbar { align-items: flex-start; flex-direction: column; }
  h1 { font-size: 42px; }
}
''';
}

String _protocolSvg() {
  return r'''
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 900 700" role="img" aria-labelledby="title desc">
  <title id="title">pqforge protocol pipeline</title>
  <desc id="desc">Payload recipes flow into post-quantum envelopes, signatures, wrapped keys, and CLI/server outputs.</desc>
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="#0b1d2f"/>
      <stop offset=".55" stop-color="#102947"/>
      <stop offset="1" stop-color="#1f2534"/>
    </linearGradient>
    <linearGradient id="accent" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="#52e0d5"/>
      <stop offset="1" stop-color="#f5c35b"/>
    </linearGradient>
  </defs>
  <rect width="900" height="700" fill="url(#bg)"/>
  <g opacity=".2" stroke="#d8f8ff" stroke-width="1">
    <path d="M80 90h740M80 180h740M80 270h740M80 360h740M80 450h740M80 540h740M80 630h740"/>
    <path d="M120 60v600M240 60v600M360 60v600M480 60v600M600 60v600M720 60v600"/>
  </g>
  <g fill="#06111d" stroke="url(#accent)" stroke-width="3">
    <rect x="70" y="84" width="250" height="96" rx="14"/>
    <rect x="70" y="234" width="250" height="96" rx="14"/>
    <rect x="70" y="384" width="250" height="96" rx="14"/>
    <rect x="580" y="126" width="250" height="96" rx="14"/>
    <rect x="580" y="276" width="250" height="96" rx="14"/>
    <rect x="580" y="426" width="250" height="96" rx="14"/>
    <circle cx="450" cy="340" r="118" fill="#07111d"/>
  </g>
  <g fill="#f7fbff" font-family="Inter, Arial, sans-serif" font-size="28" font-weight="700">
    <text x="94" y="124">Files + folders</text>
    <text x="94" y="274">Text + media</text>
    <text x="94" y="424">Webhooks + tokens</text>
    <text x="610" y="166">PqEnvelope</text>
    <text x="610" y="316">ML-DSA proofs</text>
    <text x="610" y="466">CLI + servers</text>
    <text x="384" y="324">ML-KEM</text>
    <text x="382" y="364">AEAD</text>
  </g>
  <g stroke="#52e0d5" stroke-width="5" stroke-linecap="round" fill="none">
    <path d="M320 132c74 0 80 92 156 92"/>
    <path d="M320 282c66 0 72 58 104 82"/>
    <path d="M320 432c72 0 80-78 142-88"/>
    <path d="M536 268c48-48 82-94 144-94"/>
    <path d="M558 342h120"/>
    <path d="M536 412c42 36 82 74 144 74"/>
  </g>
  <g fill="#f5c35b">
    <circle cx="450" cy="340" r="9"/>
    <circle cx="680" cy="174" r="9"/>
    <circle cx="680" cy="342" r="9"/>
    <circle cx="680" cy="486" r="9"/>
  </g>
</svg>
''';
}

String _faviconSvg() {
  return r'''
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
  <rect width="64" height="64" rx="12" fill="#07111d"/>
  <path d="M14 18h21c8 0 13 5 13 12s-5 12-13 12H26v10H14V18Zm12 10v14h8c4 0 6-3 6-7s-2-7-6-7h-8Z" fill="#52e0d5"/>
  <path d="M43 44l8 8" stroke="#f5c35b" stroke-width="6" stroke-linecap="round"/>
</svg>
''';
}

String _sitemap(JsonMap manifest) {
  final project = _map(manifest['project']);
  return '''
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url><loc>${project['canonical_url']}</loc></url>
  <url><loc>${project['canonical_url']}llms.txt</loc></url>
  <url><loc>${project['canonical_url']}llms-full.txt</loc></url>
  <url><loc>${project['canonical_url']}identity.json</loc></url>
</urlset>
''';
}

String _mdComment() => '<!-- $_generatedNotice -->';

String _repoBlob(JsonMap project, String path) {
  return '${project['repository']}/blob/${project['repository_branch']}/$path';
}

JsonMap _map(Object? value) => Map<String, dynamic>.from(value as Map);

List<JsonMap> _maps(Object? value) =>
    (value as List).map((item) => _map(item)).toList();

List<String> _strings(Object? value) =>
    (value as List).map((item) => item.toString()).toList();

String _html(String value) {
  return value
      .replaceAll('&', '&amp;')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;')
      .replaceAll('"', '&quot;');
}
